custom: ${file(../customs/${opt:stage, 'dev'}.yml)}

# サービス名
service: gg-functions

provider:
    name: aws
    runtime: python3.7
    stage: ${opt:stage, 'dev'}
    region: ${self:custom.deployRegion}
    profile: ${self:custom.profile}
    logRetentionInDays: ${self:custom.retentionInDays}
    timeout: 30
    memorySize: 256
#    logs:
#        restApi: true
#    tracing:
#        apiGateway: true
#        lambda: true
    iamRoleStatements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
#            - "xray:PutTraceSegments"
#            - "xray:PutTelemetryRecords"
          Resource: "*"

package:
    exclude:
        - tests/**
        - node_modules/**
        - .venv/**

plugins:
    - serverless-prune-plugin
    - serverless-python-requirements

# 関数定義
functions:
    pisys_monitor:
        handler: pisys_monitor_gg_handler.function_handler
