#custom: ${file(../customs/${opt:stage, 'dev'}.yml)}

custom:
    deployRegion: us-west-2
    profile: takanorig
    retentionInDays: 3

    # serverless-python-requirements
    pythonRequirements:
        fileName: ../requirements.txt

    # serverless-prune-plugin
    prune:
        automatic: true
        number: 3

    # serverless-plugin-greengrass
    # Can't define to custom-file.
    greengrass:
        groupId: 3c7c035b-c671-4815-9652-25d1b63844c8
        autoDeploy: false
        deployTimeout: 30
        defaults:
            pinned: false
            memorySize: 16384  # 16 MB expressed in KB
            timeout: 15
            encodingType: json

# サービス名
service: gg-functions

provider:
    name: aws
    runtime: python3.7
    stage: ${opt:stage, 'dev'}
    region: ${self:custom.deployRegion}
    profile: ${self:custom.profile}
    logRetentionInDays: ${self:custom.retentionInDays}
#    timeout: 30
#    memorySize: 256
#    logs:
#        restApi: true
#    tracing:
#        apiGateway: true
#        lambda: true
    iamRoleStatements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
#            - "xray:PutTraceSegments"
#            - "xray:PutTelemetryRecords"
          Resource: "*"

package:
    exclude:
        - tests/**
        - node_modules/**
        - .venv/**

plugins:
    - serverless-prune-plugin
    - serverless-python-requirements
    - serverless-plugin-greengrass

# 関数定義
functions:
    pisys_monitor:
        handler: pisys_monitor_gg_handler.function_handler
        greengrass:
            pinned: true
            accessSysfs: true
            subscriptions:
            - target: "cloud"
              subject: gg_example/#

